---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: glusterfs-storage
provisioner: kubernetes.io/glusterfs
parameters:
  resturl: "http://10.244.1.6:8080"
  restuser: "admin"
  restuserkey: "admin@cps2024"
  volumetype: "replicate:3"